# Generated by Django 4.2.1 on 2023-05-12 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='instrumentos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(max_length=200)),
                ('precio', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ventas',
            fields=[
                ('idventa', models.AutoField(primary_key=True, serialize=False)),
                ('Total', models.IntegerField(blank=True, null=True)),
                ('Fecha', models.DateTimeField()),
            ],
        ),
    ]
